### ISSUE TITLE
MWS layer not loading due to security restrictions

### ISSUE THREAD

**Issue by ekkelenkamp** [Sumbera/WMSOnMapKit-iOS7#1]
Thanks for the nice demo on how to load WMS layers on top of mapkit.
Unfortunately the current demo doesn't work with IOS 9 due to security restrictions. Layers have to be loaded over https.

One way to work around it, is to add the following to the WMSOnMapKit-Info.plist.

```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```

Regards,

Rudie.

**Comment by Sumbera** [comment]
Hi Rudi, good catch, thanks!
